//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/opendatahub-io/openshift-ai-lightspeed-operator/pkg/common/condition"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeed) DeepCopyInto(out *OpenShiftAILightspeed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeed.
func (in *OpenShiftAILightspeed) DeepCopy() *OpenShiftAILightspeed {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAILightspeed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeedCore) DeepCopyInto(out *OpenShiftAILightspeedCore) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeedCore.
func (in *OpenShiftAILightspeedCore) DeepCopy() *OpenShiftAILightspeedCore {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeedCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeedDefaults) DeepCopyInto(out *OpenShiftAILightspeedDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeedDefaults.
func (in *OpenShiftAILightspeedDefaults) DeepCopy() *OpenShiftAILightspeedDefaults {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeedDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeedList) DeepCopyInto(out *OpenShiftAILightspeedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenShiftAILightspeed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeedList.
func (in *OpenShiftAILightspeedList) DeepCopy() *OpenShiftAILightspeedList {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenShiftAILightspeedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeedSpec) DeepCopyInto(out *OpenShiftAILightspeedSpec) {
	*out = *in
	out.OpenShiftAILightspeedCore = in.OpenShiftAILightspeedCore
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeedSpec.
func (in *OpenShiftAILightspeedSpec) DeepCopy() *OpenShiftAILightspeedSpec {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenShiftAILightspeedStatus) DeepCopyInto(out *OpenShiftAILightspeedStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(condition.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenShiftAILightspeedStatus.
func (in *OpenShiftAILightspeedStatus) DeepCopy() *OpenShiftAILightspeedStatus {
	if in == nil {
		return nil
	}
	out := new(OpenShiftAILightspeedStatus)
	in.DeepCopyInto(out)
	return out
}
